### ISSUE TITLE
 Не работает zoom fit

### ISSUE THREAD

**Issue by aurusov** [AlexChernov/rdo_studio#18]
Для раскладки `5 2 1 4 0 3`

![2014-11-15 08-27-58 ubuntu x64 running](https://cloud.githubusercontent.com/assets/5585202/5056646/570912e4-6ca1-11e4-99f9-7fd27ae3dfb3.png)

**Comment by bogachev-pa** [comment]
Решил не создавать отдельную таску, потому что очень близкий баг. Если надо, вынесу отдельно.

Hotkey для Zoom-in работает странно.
Горячие клавиши для Zoom-in/Zoom-out в окне просмотра графа это `Ctrl^+` и `Ctrl^-` соответственно. Однако чтобы сделать Zoom-in нужно нажать `Ctrl^Shift^+`.

Я имею в виду '+', который находится на одной кнопке с '='. Видимо, так как '+' это 'Shift^=', но гуи ожидает именно его, а не просто нажатие '='. 
С плюсом на нампаде всё окей. Я так думаю, это всё-таки не ожидаемое поведение.

Еще немного странно, что зум-ин и зум-аут работают по `Shift` + колесо мыши, а не по `Ctrl` + колесо мыши, как вроде везде принятно. Ну то есть обычно, с `Alt` скроллим горизонтально, с `Shift` вертикально, а с `Ctrl` зумим. А тут `Ctrl` и `Shift` перепутаны.

Еще один момент, не знаю, надо ли его выносить в отдельную таску:

Окошко с графом нельзя развернуть на полный экран, ни кнопки ни опции по правому щелчку мыши нет, это как-то неудобно.

Наблюдал всё на версии с [форума](http://www.rdostudio.com/phpbb/viewtopic.php?f=9&t=32).

**Comment by AlexChernov** [comment]
1. Не баг, много где так, без примеров.
2. Не уверен, что у модального окна должны быть кнопки свернуть и развернуть

**Comment by aurusov** [comment]
1. Были те же мысли. В Firefox'е
   - увеличить двумя способами `Ctrl +`, который превращается в `Ctrl Shift +`, и `Ctrl =`
   - уменьшить одним `Ctrl -` (`Ctrl _` не работает на уменьшение)
     Выглядит удобным, предлагаю добавить
2. Тоже показалось странным. Если придираться, то окно не обязано быть модальным. Переделывать не надо, просто модальность означает невозможность работы с другими окнами, оно как бы становиться главным. Но почему оно должны быть без кнопки развернуть - мне не понятно. Если нет явный причин против, то лучше добавить.

**Comment by bogachev-pa** [comment]
Еще насчет `Zoom-fit`.
У меня лично не работает не только сама кнопка, но вообще нельзя сделать изображение меньше, чем оно было изначально. Причем всё это выглядит очень странно, допустим, я открываю граф первый раз, там всё нормально. Потом с каждым новым запуском изначальный зум становится всё сильнее и сильнее. В какой-то момент вершины графа становятся просто огромными и с ним невозможно дальше работать, при этом отдалиться нельзя никак.
После перезапуска РДО изначальный зум сбрасывается, но дальше всё повторяется сначала.

Это под виндой, в версии с форума.

Я не знаю, это известный баг или нет, но его точно надо пофиксить до пятницы, когда по пятнашкам будут лабы.

**Comment by AlexChernov** [comment]
@bogachev-pa Нужны скриншоты, без них не понятно.

**Comment by bogachev-pa** [comment]
Собрал твои исходники, теперь всё хорошо.

**Comment by bogachev-pa** [comment]
Поправка: почти всё хорошо.
При закрытии РДО ловлю 

```
Unhandled exception at 0x5623AD16 (Qt5Cored.dll) in rdo_studio.exe: 0xC0000005: Access violation reading location 0xFEEEFF12.
```

Собирал под виндой в MVS 2012.

Но к этому issue отношения, наверное, не имеет. Попробуй воспроизвести.

**Comment by AlexChernov** [comment]
Работаю над этим, воспроизводится везде и всегда при закрытии с загруженным плагином

**Comment by aurusov** [comment]
Это ошибка владения объёктом model. Боль. Она же мешает создать модель пятнашек в первый раз. Надо отрефакторить всё это нафиг. Не уверен, что успею до лабы.

@AlexChernov 
Как самое простое решение: кидать сигналы о создании и удалении модели. Отлавливать в плагине и обновлять указатель в плагине. Кидать должно приложение. Думаю, что не смогу раньше среды приступить к решению.

**Comment by AlexChernov** [comment]
#27
