### ISSUE TITLE
Скобки в имени эвристики

### ISSUE THREAD

**Issue by bogachev-pa** [AlexChernov/rdo_studio#22]
Очень напрягает необходимость ставить скобки в имени эвристики.
![brackets](https://cloud.githubusercontent.com/assets/6528492/5114409/cbce5ab8-7051-11e4-83de-79431f96e805.png)

К тому же имена стандартных эвристик без скобок и это сбивает с толку.
Леша, можешь это выпилить?

А еще было бы супер круто иметь больше одной строчки для собственных эвристик. Или иметь возможность пользователю их добавить. Я, например, сравниваю две свои эвристики и мне приходится их перевбивать.

**Comment by AlexChernov** [comment]
Скобки, это ограничения рдо, ведь эвристика – это просто функция, могу добавить скобки в 2 стандартных эвристиках, чтобы не сбивало с толку.

**Comment by aurusov** [comment]
Скобки можно дописывать автоматом, если их нет

Конечно, надо проверить с учётом ситуации `Эвристика(a, b, c)`

**Comment by bogachev-pa** [comment]
> Конечно, надо проверить с учётом ситуации Эвристика(a, b, c)

Действительно, я сначала не подумал об этом случае.
Может быть стоит разрешить обе конструкции `Эвристика` и `Эвристика()`, если у неё нет параметров, но если параметры есть, обязать писать `Эвристика(a, b, c)`. Тогда можно и не ставить скобки в именах стандартных эвристик (это всё-таки не очень красиво).

**Comment by aurusov** [comment]
Я не понимаю о чём спор. В строке ищется символ `(`. Если его нет, то добавляется `()` в самый конец. Мы обсуждаем это больше.

**Comment by AlexChernov** [comment]
В эту строку можно написать хоть 

``` cpp
5 * МояЭвристика() - 7 //Моя эвристика
```

Тем не менее раз уж я распарсил имена всех функций, я могу искать их в этой строке и добавлять скобочки, раз есть такое пожелание

**Comment by aurusov** [comment]
Да, про комментарии в конце не подумал. Тогда вообще фигово, как бы не изголялись. 
`5 * МояЭвристика - 7 // МояЭвристика() * 100500`

Без компилятора эту строчку не распарсить. Можно предложить следующее
Убедиться, что в строке вбито только одно слово (без пробелов) без комментариев (нет `// /*` или просто нет `/`). Плюс условие про скобку выше.

**Comment by bogachev-pa** [comment]
Возможно удобнее всего будет просто настоить автодополнение, чтобы оно сразу ставило скобки.

**Comment by aurusov** [comment]
В Qt есть что-то подобное ? Тогда в тот объект можно добавить логику от моего пред. поста.

**Comment by bogachev-pa** [comment]
В общем, необходимость ставить скобочки вызвала мучительные проблемы с поиском ошибки как минимум у одного человека из нашей группы.
Я думаю, надо что-то с ними всё-таки делать. Предлагаю как минимальный вариант поставить скобочки в примерах эвристик тоже, а потом уже выдумывать что-то еще.

**Comment by aurusov** [comment]
Скобки добавил, на форум выложил
https://github.com/aurusov/rdo_studio/releases

Предлагаю закрыть, т.к. другие решения кажутся неоправлано сложными. Вернёмся к теме, если возникнет необхожимость.
