### ISSUE TITLE
Исправить параметры запуска

### ISSUE THREAD

**Issue by aurusov** [AlexChernov/rdo_studio#23]
`--autorun` с запуском плагина пятнашек привожит к неожидаемым результатам. Хотя должен приводить к однозначным

1 `.\rdo_studio.exe --plugin0="1 0 2 4 5 3" -i C:\rdo\rdo_models_test\plugin\game5_test` - запуск плагина (генерации модели)
2 `--autorun` - запуск модели после её генерации
3 `--autoexit` - закрытие студии или после отработки модели

Если `--autorun` не указан, то `--autoexit` зыкрывает студию после генерации модели. Т.е. возможны ситуации
1 + 2 + 3
1 + 2 (студия не закрывается)
1 + 3

**Comment by AlexChernov** [comment]
autoexit по документации должен закрыть после прогона разве, нет?

**Comment by aurusov** [comment]
Да, именно так. Но тогда не было плагинов. А сейчас от него надо только сгенерировать модели и выйти. Чтобы не городить новых параметров, предлагаю использовать этот, а документацию подправить.

**Comment by AlexChernov** [comment]
Окончательный вариант .\rdo_studio.exe --plugin0="1 0 2 4 5 3" -i C:\rdo\rdo_models_test\plugin\game5_test . Плагин вызывает метод quit() QApplication
