### ISSUE TITLE
Исправить проброс параметров плагина

### ISSUE THREAD

**Issue by aurusov** [AlexChernov/rdo_studio#24]
Как я понял, сейчас параметр запуска `--plugin0="1 0 2 4 5 3"` означает - передай `"1 0 2 4 5 3"` первому плагину из списка плагинов. Правильно ? Если так, то это ошибка: что будет, если плагинов станет два и пятнашки окажутся вторыми ?

Предлагается передавать или
1 все параметры запуска каджому плагины (все, вообще все, даже со строкой бинарника) и пусть каждый плагин разбирается: `game5_plate="1 0 2 4 5 3"`
или
2 или предусмотреть передачу имени плагина, например на основе названия dll'ки: `--plugin_plugin_game5="1 0 2 4 5 3"`

**Comment by AlexChernov** [comment]
--pluginlist даст знать какой id запускать

1/2. Если плагина станет 2, то оба смогут запуститься с game5_plate="1 0 2 4 5 3"; --plugin_plugin_game5="1 0 2 4 5 3"

**Comment by aurusov** [comment]
> --pluginlist даст знать какой id запускать

Я не знаю, какой id у какого плагина. Как этим можно думать ?

> 1/2. Если плагина станет 2, то оба смогут запуститься с game5_plate="1 0 2 4 5 3"; --plugin_plugin_game5="1 0 2 4 5 3"

Не понимаю. Если два плагина пятнашек ? Тогда у них будут разные имена в *.dll. Т.е. надо использовать вторую схему.

**Comment by AlexChernov** [comment]
Plugins\version1_debug\plugin_game5.dll
Plugins\version2_release\plugin_game5.dll
Plugins\format_c_plugin\plugin_game5.dll

**Comment by aurusov** [comment]
Это пример того, что плагины ищутся рекурсивно ? Тогда нужно вводить уникальный идентификатор плагина, например, `GUID`.

**Comment by AlexChernov** [comment]
@aurusov Можно я это закрою? Вряд ли у нас появятся еще плагины
