### ISSUE TITLE
Перестал выводится диалог при запуске из консоли

### ISSUE THREAD

**Issue by aurusov** [AlexChernov/rdo_studio#25]
https://github.com/AlexChernov/rdo_studio/commit/13d9c0342d44cb3ba5900cf59b1d73b02b82ac55

**Comment by AlexChernov** [comment]
Не воспроизводится.
Запуск 1:
![alt text](https://dl.dropboxusercontent.com/u/83045139/Issue25.1.png)
В диалоге выбрал Yes
Запуск 2:
![alt text](https://dl.dropboxusercontent.com/u/83045139/Issue25.2.png)
Плагин отработал без вызова диалога
Запуск 3(копия в другой дирректории):
![alt text](https://dl.dropboxusercontent.com/u/83045139/Issue25.3.png)

**Comment by aurusov** [comment]
Это хорошо. Но на сервере воспроизводится (описано тут https://github.com/AlexChernov/rdo_studio/commit/13d9c0342d44cb3ba5900cf59b1d73b02b82ac55#commitcomment-8649811).

**Comment by aurusov** [comment]
Какую ветку собирал ? Собири именно её на дженкинсе в новой задаче.

**Comment by AlexChernov** [comment]
Честно говоря, я сейчас на работе, поэтому просто выкачал бинарник rdo-studio-AlexChernov-dev-vs-release, все равно сделать новую задачу?

**Comment by aurusov** [comment]
Да, обязательно. Она создаётся как копия существующей. Нужно честно провести эксперимент. У тебя много веток, надо зафиксировать. Пусть всё будет написано в отдельной таске, в которую ты не будешь лазить и менять. Ведь запуск плагина ты перевёл на питон, но не для всех сборок. Вот для этой не надо :) Пусто она будет read-only

**Comment by AlexChernov** [comment]
@aurusov История появления read-only сборки
