### ISSUE TITLE
CmakeList, сборка под msvs

### ISSUE THREAD

**Issue by AlexChernov** [AlexChernov/rdo_studio#26]
Плагин пятнашек не копируется в папку .\plugins,  а валяется в папке со всеми бинарниками.

**Comment by AlexChernov** [comment]
@aurusov 
Разгадка провала сборок под vs

**Comment by aurusov** [comment]
Да, тоже вчера обнаружил. Но не смотрел cmake. Когда собирается через Visual Studio, то всё хорошо. На сервере собирается через jom. Надо курить доки.
