### ISSUE TITLE
Segmentation fault при закрытии РДО

### ISSUE THREAD

**Issue by AlexChernov** [AlexChernov/rdo_studio#27]
При закрытии РДО, в которой запущен плагин, рдо падает с ошибкой Segmentation fault.

```
Unhandled exception at 0x5623AD16 (Qt5Cored.dll) in rdo_studio.exe: 0xC0000005: Access violation reading location 0xFEEEFF12.
```

**Comment by aurusov** [comment]
Закрытие исправилось ? А первый запуск пятнашек ?

**Comment by AlexChernov** [comment]
Закрытие исправилось. Первый запуск - нет.
Попробуйте отключить плагин, если он был в автозагрузке, создать новую модель, вставить в первую вкладку что-нибудь типа:

```
$ЯвноНекомпилируемыйКод
    result = "Плагин Не Виноват"
$End
```

И запустить

**Comment by aurusov** [comment]
Ну хоть закрытие пофиксили. Создавай пул реквест на все последние изменения.

А по первому запуску заведи отдельную таску на меня.
