### ISSUE TITLE
Тестирование пятнашек

### ISSUE THREAD

**Issue by aurusov** [AlexChernov/rdo_studio#3]
Из консоли можно запустить rdo_studio. Пример выводит хелп в консоль и завершает работу студии
`./rdo_studio -platform minimal --help --gui_silent_mode`

Предлагается
- Добавить параметры запуска. Список подсмотреть у rdo.exe. Его надо осмыслить, почистить. Но главное, непонятно как применить вычитанные параметры. Потому что вычитываются они до создания главного окна. Запускать полноценный палагин в этот момент еще глупо.
- Один из параметров должен указывать имя плагина, который надо запустить. Надо научиться запускать плагин
- Другой параметр должен содержать параметра запуска плагина. Их надо пробросить в плагин.
- Третий параметр должен завершить и плагин и rdo_studio после работы плагина
- На выходе получаем сгенерённый код модели, который скармливаем rdo.exe. Если он содержит ошибки, то Дженкинс нам их покажет.

**Comment by AlexChernov** [comment]
http://rdo.rk9.bmstu.ru:81/view/AlexChernov_dev/job/rdo-studio-AlexChernov-dev-ubuntu-14-04-x86-debug/18/console

**Comment by aurusov** [comment]
Круто. А кто проверяет результаты ?

**Comment by AlexChernov** [comment]
executor_of_system_tests

**Comment by aurusov** [comment]
Опиши подробнее как это происходит. Опиши так, чтобы потом сразу вставить в РПЗ.

**Comment by AlexChernov** [comment]
В репозитории https://github.com/AlexChernov/rdo_models_test.git, в /dev/plugin/game5_test хранятся пустая модель и эталонный файл трассировки.
Пустая модель передается в качестве аргумента для параметра --input  при запуске rdo_studio

``` bash
GAME5_TEST_MODEL=`pwd`/../models/test/plugin/game5_test/game5_test.rdox
/rdo_studio -platform minimal --game5_testcase="1 0 2 4 5 3" -i $GAME5_TEST_MODEL
```

При запуске с этими параметрами будет открыта эта модель, изменена в соответствии с моделью пятнашек для начального положения переданного как аргумент параметра `--game5_testcase` (в  данном случае 1 0 2 4 5 3) и сохранена, после этого rdo_studio закрывается.
Далее созданная модель проходит стандартный тест executor_of_system_tests
Файл теста  game5_test.rtestx:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<test>
  <model name="game5_test.rdox" target="CONSOLE" exit_code="0"/>
  <etalons>
    <file source="game5_test.trc" target="etalons/game5_test.trc" type="TRACE"/>
  </etalons>
</test>
```

**Comment by aurusov** [comment]
ok

Полный путь тоже можно писать
https://github.com/AlexChernov/rdo_models_test/tree/dev/plugin/game5_test

PS: используй раскраску синтаксиса.
