### ISSUE TITLE
Возможная ошибка в алгоритме поиска по графу

### ISSUE THREAD

**Issue by bogachev-pa** [AlexChernov/rdo_studio#32]
@aurusov 
@AlexChernov 
Пытался сделать поиск в глубину. Для этого в верху вкладки `FUN` написал следующее:

```
$Resource_type InDepthCounter: permanent
$Parameters
    count : integer = 1000
$End

$Resources
    Counter = InDepthCounter(*);
$End

$Function InDepthSearch: real
$Type = algorithmic
$Parameters
$Body
    Counter.count -= 2;
    return Counter.count;
$End
```

Ну и соответственно выбираю эвристику `InDepthSearch()`.
Результат - РДО зависает в бесконечной попытке найти решение, при этом явно что-то делает и валит трассировку.
Если запускали из плагина, то в конце выдается одна диагональная линия вместо графа.

Если поменять `Counter.count -= 2;` на `Counter.count -= 1;`, решение находится, но получаем тоже забавные явления. 
Например 733 вершины в графе и 588 раскрытых.

@k-alexandrovsky
Кирилл, тебе это тоже должно быть интересно, в связи с имплементацией dpt-search в новом рдо. Чуть позже проверю, как с этим справляется твой алгоритм.

**Comment by aurusov** [comment]
Отрицательные эвристики - это не очень хорошо. Хотя да, алгоритмически такое работать должно. Где-то ошибка. Сейчас не готов дебажить, есть чем заняться. Если кто-то может по времени, то проанализируйте трассировку.

**Comment by bogachev-pa** [comment]
> Отрицательные эвристики - это не очень хорошо. 

Дело точно не в отрицательности, если поставить 1000000 вместо 1000 будет то же самое.

**Comment by bogachev-pa** [comment]
В общем, судя по трассировке, алгоритм попадает в бесконечный цикл, гоняя фишки по кругу.
Выдержка из трассировки (добавил пробелов для читабельности):

```
SO 20497 2.049e+04 8199 9.18e+04

STN 20499 20497 8200 9.18e+04 1 1 1 2  1 6
SRK 0 1 1 1 2
SRK 0 2 6 1
STN 20500 20497 8200 9.18e+04 2 1 1 2  2 6
SRK 0 1 2 2 2
SRK 0 2 6 3
STN 20501 20497 8200 9.18e+04 3 1 1 2  5 6
SRK 0 1 5 5 2
SRK 0 2 6 5

SO 20499 2.05e+04 8200 9.18e+04

STN 20502 20499 8201 9.18e+04 2 1 1 2  1 6
SRK 0 1 1 1 1
SRK 0 2 6 2
STN 20503 20499 8201 9.18e+04 3 1 1 2  4 6
SRK 0 1 4 4 1
SRK 0 2 6 4

SO 20502 2.05e+04 8201 9.18e+04

STN 20504 20502 8202 9.18e+04 1 1 1 2  1 6
SRK 0 1 1 1 2
SRK 0 2 6 1
STN 20505 20502 8202 9.18e+04 2 1 1 2  2 6
SRK 0 1 2 2 2
SRK 0 2 6 3
STN 20506 20502 8202 9.18e+04 3 1 1 2  5 6
SRK 0 1 5 5 2
SRK 0 2 6 5

SO 20504 2.05e+04 8202 9.18e+04

STN 20507 20504 8203 9.18e+04 2 1 1 2  1 6
SRK 0 1 1 1 1
SRK 0 2 6 2
STN 20508 20504 8203 9.18e+04 3 1 1 2  4 6
SRK 0 1 4 4 1
SRK 0 2 6 4
```

И так далее много раз повторяется.

Все вершины в трассировке `STN`, т.е. новые. Видимо, косяк где-то в этом. Псевдо-эвристика для поиска в глубину гарантирует, что у каждой новой вершины значение `f` будет меньше, чем у всех предыдущих. Поэтому если алгоритм считает вершины новыми, то он и будет их бесконечно гонять.

В новом РДО проблема точно такая же. Я, правда, не в точности такую модель там написал, потому что так не работает, но, как мне кажется, аналогичную.

**Comment by bogachev-pa** [comment]
В общем, всё круто.
Как правильно догадался Кирилл, косяк был в моем алгоритме. Он добавляет новый ресурс, и меняет ему параметр, что меняет состояние базы данных системы. Потому раскрытые вершины и считаются новыми.

Я сделал правильный поиск в глубину с использованием просто огромной `enumerative` последовательности. С ним никаких косяков не наблюдается.
