### ISSUE TITLE
Автоматический масштаб для графа результатов

### ISSUE THREAD

**Issue by aurusov** [AlexChernov/rdo_studio#8]
- Размеры окна менять на надо, путь берутся с пред. просмотра. При первом запуске брать размеры из дизайнера.
- Предлагается не менять масштаб самого графа, если его максимальная ширина изменилась менее, чем на 10%. В противном случае - полный пересчет масштаба.
- Предусмотреть сброс масштаба в 1:1 по hotkey
- Предусмотреть пересчет автомасштаб по hotkey

**Comment by AlexChernov** [comment]
> Предлагается не менять масштаб самого графа, если его максимальная ширина изменилась менее, чем на 10%. В противном случае - полный пересчет масштаба.

Сохранение масштаба кажется лишним, изменил на 1:1 при перестроении

**Comment by aurusov** [comment]
Аргументируй.

**Comment by AlexChernov** [comment]
Монструозность графа на старом масштабе, в общем случае, связана не с изменением максимальной ширины, а просто со значением масштаба.

**Comment by aurusov** [comment]
Без примеров не понимаю. 1:1 кажется не самым удачным решением, лучше вписать граф в отведенное место imho.

**Comment by aurusov** [comment]
В режиме автоматического масштаба изменять масштаб автоматически при измении размеров окна. Сбрасывать признак автоматическго масштаба, как только юзер поменял его самостоятельно.
